# @package _global_
data:
  train_path: data/mozilla_train_manifest.json
  val_path: data/mozilla_dev_manifest.json
  num_workers: 4
  augmentation:
    spec_augment: True
trainer:
  max_epochs: 250
  gpus: 1
  precision: 16
  gradient_clip_val: 400  # Norm cutoff to prevent explosion of gradients
  accelerator: ddp
  plugins: ddp_sharded
  checkpoint_callback: True
checkpoint:
  save_top_k: 15
  monitor: "cer"
  verbose: True
  dirpath: './models'
  prefix: 'ckpt'
  save_last: False
  mode: auto
  period: 1
